### ISSUE TITLE
Red hue for hero

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Institute-for-Survey-Research#2]
Hey Zac Attack! Would you be able to put the red hue on this hero image to make the text stand out? Thanks so much! 
![isr hero](https://user-images.githubusercontent.com/15130721/39881368-bb5ccca2-544e-11e8-93a9-5a5d61cab468.jpg)

**Comment by ZMcGroarty** [comment]
![hero_isr](https://user-images.githubusercontent.com/15017242/40058375-f7ef954a-581e-11e8-8b73-d2227aa81fda.png)

**Comment by CVE82** [comment]
Thank you so much!!
