### ISSUE TITLE
Faculty List appears in footer

### ISSUE THREAD

**Issue by lidopaglia** [TULiberalArts/Institute-for-Survey-Research#3]
"Faculty List" link is broken in the footer.

**Comment by lidopaglia** [comment]
fixed in c966b644144415ffd920996158c4d368630b8562 by removing the empty staff page.

**Comment by lidopaglia** [comment]
Still a problem. Perhaps caching related or something of the like. will investigate.

**Comment by tu-chill** [comment]
Lido and Magic
